[package]
name = "etxdbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }
colored = "2.0"
prost = "0.11"
thiserror = "1.0.40"
tokio = { version = "1.26", features = ["full"] }
tokio-serial = "5.4"

[build-dependencies]
prost-build = "0.11"
