[package]
name = "etxdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }
colored = "2.0"
env_logger = "0.10.0"
prost = "0.11"
prost-types = "0.11.8"
serialport = "4.2.0"

[build-dependencies]
prost-build = "0.11"
