name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: sudo apt update && sudo apt install protobuf-compiler -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: brew install protobuf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  # build:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install protoc
  #     run: sudo apt install protobuf-compiler -y
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose
