name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: |
        PROTOC_VERSION=$(curl -s "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
        curl -Lo protoc.zip "https://github.com/protocolbuffers/protobuf/releases/latest/download/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
        sudo unzip -q protoc.zip bin/protoc -d /usr/local
        sudo chmod a+x /usr/local/bin/protoc
        protoc --version
        rm -rf protoc.zip
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: brew install protobuf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  # build:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install protoc
  #     run: sudo apt install protobuf-compiler -y
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose
